More runtime checks.
I'm not sure how portable these are - I expect we'll iterate a few times
to find something portable.

You should expect to see some spurious warnings from gcc as it
complains about perfectly legal but unusual code (like giving a
function prototype for gcc builtin functions).

The output I see from these tests is:

./../src/hugs +q +w -pHugs: -P../lib:../lib/hugs:../lib/exts +G ffi/Sin.hs < /dev/null
expected stderr not matched by reality
*** /tmp/no_stderr27731 Tue Jun 18 21:34:24 2002
--- /tmp/runtest27731.2 Tue Jun 18 21:34:24 2002
***************
*** 0 ****
--- 1,2 ----
+ Sin.c: In function `hugsprim_sin_3':
+ Sin.c:51: warning: built-in function `sin' declared as non-function
-- !!! Testing static, dynamic and wrapped import of trig function
-- !!! Testing marshalling of strings
./../src/hugs +q +w -pHugs: -P../lib:../lib/hugs:../lib/exts +G ffi/String.hs < /dev/null
expected stderr not matched by reality
*** /tmp/no_stderr27767 Tue Jun 18 21:34:25 2002
--- /tmp/runtest27767.2 Tue Jun 18 21:34:25 2002
***************
*** 0 ****
--- 1,3 ----
+ MarshalUtils.c: In function `hugsprim_memcpy_0':
+ MarshalUtils.c:22: warning: conflicting types for built-in function `memcpy'
+ MarshalUtils.c:22: warning: extern declaration of `memcpy' doesn't match global one
-- !!! Testing marshalling of strings
-- !!! Testing system calls
./../src/hugs +q +w -pHugs: -P../lib:../lib/hugs:../lib/exts +G ffi/FileIO.hs <
/dev/null
expected stderr not matched by reality
*** /tmp/no_stderr27827 Tue Jun 18 21:34:25 2002
--- /tmp/runtest27827.2 Tue Jun 18 21:34:26 2002
***************
*** 0 ****
--- 1,3 ----
+ MarshalUtils.c: In function `hugsprim_memcpy_0':
+ MarshalUtils.c:22: warning: conflicting types for built-in function `memcpy'
+ MarshalUtils.c:22: warning: extern declaration of `memcpy' doesn't match global one
-- !!! Testing system calls